version: '3.3'

services:
  keycloak:
    image: "quay.io/keycloak/keycloak:26.3.2"
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DEBUG: "true"
      DEBUG_PORT: '*:8787'
    entrypoint: /bin/bash
    command: -c "/opt/keycloak/bin/kc.sh start-dev --spi-events-listener-last-login-timer=20 --verbose --features=declarative-ui"
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8787:8787"
    expose:
      - 8080
      - 8787
    volumes:
      - ./deployments/:/opt/keycloak/providers/
